In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Restaurant_Reviews.tsv',delimiter='\t',quoting=3)#quoting 3 to ignore double quotatrions

In [3]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [4]:
#cleaning data

In [5]:
x1 = dataset['Review'][0]
x1

'Wow... Loved this place.'

In [6]:
import re
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [7]:
x1 = re.sub('[^a-zA-Z]',' ',x1)

In [8]:
x1 = x1.lower()

In [9]:
x1 = x1.split()

In [10]:
x1 = [word for word in x1 if not word in set(stopwords.words('english'))]#removing the stop words

In [11]:
x1

['wow', 'loved', 'place']

In [12]:
#stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [13]:
#ps.stem('loved')

In [14]:
x1 = [ps.stem(word) for word in x1 ]

In [15]:
x1

['wow', 'love', 'place']

In [16]:
#converting back to string
x1 = ' '.join(x1)

In [17]:
x1

'wow love place'

In [18]:
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [19]:
len(corpus)

1000

In [20]:
#bag of words model

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [22]:
cv = CountVectorizer()

In [23]:
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,1].values

In [24]:
X.shape

(1000, 1565)

In [25]:
def evaluate(cm):
    tn = cm[0][0]
    fp = cm[0][1] 
    fn = cm[1][0]
    tp = cm[1][1]
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = (tp)/(tp+fp)
    recall = tp/(tp+fn)
    return accuracy,precision,recall
    

In [26]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
"""
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
"""

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_nb = confusion_matrix(y_test, y_pred)


C:\Users\chall\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [27]:
cm_nb

array([[55, 42],
       [12, 91]])

In [28]:
accuracy_nb,precession_nb,recall_nb = evaluate(cm_nb)
accuracy_nb

0.72999999999999998

In [29]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
"""
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)"""

# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_dt = confusion_matrix(y_test, y_pred)

In [30]:
accuracy_nb,precession_nb,recall_nb = evaluate(cm_dt)
accuracy_nb

0.70499999999999996

In [38]:
#cleaning data
corpus_predict1 = []
for i in range(0, 1):
    review = re.sub('[^a-zA-Z]', ' ', 'not_good')
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
    review = ' '.join(review)
    corpus_predict1.append(review)
classifier.predict(cv.transform(corpus_predict1))

array([0], dtype=int64)

In [35]:
corpus_predict1

['good']

In [42]:
#cleaning data
corpus_predict = []
for i in range(0, 1):
    review = re.sub('[^a-zA-Z]', ' ', 'best')
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
    review = ' '.join(review)
    corpus_predict.append(review)
classifier.predict(cv.transform(corpus_predict))

array([1], dtype=int64)

In [43]:
corpus_predict

['best']